### ISSUE TITLE
Max amp channel mismatch between units in 'clusters' alf object and phy

### ISSUE THREAD

**Issue by jaib1** [int-brain-lab/ibllib#115]
**Describe the bug**
The `'channels'` field in a `clusters` alf object that is returned in an alf directory by running `ephys.spikes.ks2_to_alf` doesn't always give the same channel as displayed in phy for a particular unit.

![mismatch_ch_phy_alf](https://user-images.githubusercontent.com/14895866/68761883-f3548c00-060c-11ea-9037-b1f4947ab060.PNG)

@oliche if you can point me to 1) the code that does the extraction for a `clusters` object from a ks2 output directory and 2) the tests for this code, I can start by writing a test that should pass, but fails, and then try and find where the bug is.

**Comment by rossant** [comment]
what is the channel mapping in this case? There is an ambiguity in the channel that can be displayed in phy: is it (1) the internal channel id, ranging from 0 to `n_channels-1`, or (2) the corresponding column in the raw data 2D array. The correspondance between the 2 is given by `channel_map.npy`.

**Comment by jaib1** [comment]
It's the first, the internal channel ID. 
> There is an ambiguity in the channel that can be displayed in phy

How does this arise?

**Comment by rossant** [comment]
Shall we display the internal channel ID, or the column index? Initially we displayed the internal ID, but we switched to the latter after user feedback... I don't know which one makes more sense for users!

**Comment by jaib1** [comment]
I would be in favor of giving the channel as the raw data's column index as well. I guess in either case what's given in alf extraction via `ephys.spikes_ks2_to_alf` should match phy. Since phy gives the raw data column index, do you know where in ibllib code this difference is?

**Comment by jaib1** [comment]
@rossant @oliche Following up on this - forgot to mention at meeting. This is a bit urgent because it's being used to calculate some metrics/plots for the V1 certification.

**Comment by oliche** [comment]
We've discussed this last week: it's a merge issue so this is moot.
Right now we should focus on re-exctracting those with the latest version
that does not merge the probes, and take it from there.

**Comment by jaib1** [comment]
@oliche should I close this then?
