### ISSUE TITLE
Ephys extractions questions

### ISSUE THREAD

**Issue by rossant** [int-brain-lab/ibllib#118]
- In `clusters.uuids.csv`, should we add a column `cluster_id` (as in cluster_metrics?)
- In `clusters.metrics.csv`, the `cluster_id` column seems to be duplicated?
- Should we switch to tsv for consistency with other ephys files?
- ibllib should save the params file required by phy, how should it be named? `phy.params.py`? (at the moment, it contains the sampling rate, the path to the raw data, the data type, the number of channels in the raw data...)
- Relatedly, before releasing pykilosort, Marius would want a GUI similar to [the GUI provided by the MATLAB version](https://github.com/MouseLand/Kilosort2/wiki/1.-The-GUI) (written by Nick), used to (1) examine the raw data, (2) set the spike sorting parameters, (3) check the bad channels on a graphical representation of the probe after preprocessing, (4) check the filtered data, (5) launch the spike sorting (perhaps on a small sample of the data to check the spike sorting parameters), (6) launch phy by clicking on a button. We could also have a table with all datasets on the local server, showing which are sorted and which are not, etc.

![](https://raw.githubusercontent.com/MouseLand/Kilosort2/master/Docs/img/ksGUI.PNG)

**Comment by oliche** [comment]
Should we extract the raw waveforms for each spike ?
