### ISSUE TITLE
one.search

### ISSUE THREAD

**Issue by kdharris101** [int-brain-lab/ibllib#12]
Thanks Cyrille for that last post. The conversation is now shifting to a different (but related) topic, so i created a new issue.

Could we actually incorporate generic Django queries into one.search? The current example we have in the notebook is

```
eid, ses = one.search(users='olivier', date_range=['2018-08-24', '2018-08-24'])
```

If this was a django filter command on the sessions table, the first one (`users='olivier'`) would I think work exactly as intended. The second one would require a different syntax. The most common query - for a list of required dataset types that must all be associated to the session - I don't think can be done by a single django filter command.

But could we have something where there are a list of "reserved words" in the one.search command, which trigger pre-defined searches, and anything else goes through as a django filter command? So for example in

```
one.search(dataset_types=['spikes.times', 'spikes.clusters'], subject__virus_injection__virus_batch__contains='Pvalb')
```
the first argument would be intercepted by the one.search code, and the second would go right through as an additional Django filter?

**Comment by rossant** [comment]
Technically, yes, we can have reserved keyword arguments as you describe.
For future reference: `dataset_types = kwargs.pop('dataset_types', None)` removes the `dataset_types` key from the `kwargs` dictionary. After repeating this with all reserved keywords, the remaining ones are the ones to be passed to django.

**Comment by kdharris101** [comment]
Great!

At the GA meeting I will ask everyone what kind of searches they will want to perform. After that (assuming anyone actually says anything, which they might not), we can get serious about making a list of all search terms we will want (similar to the list of dataset types).

**Comment by rossant** [comment]
Closing here and continuing the discussion on the ONE v2 proposal
