### ISSUE TITLE
plot_peth example no longer works

### ISSUE THREAD

**Issue by cskrasniak** [int-brain-lab/ibllib#121]
When running `brainbox_plot_peth_func.py` on the brainbox branch, I get this error: ```IndexError                                Traceback (most recent call last)
<ipython-input-19-95006cf2877c> in <module>
      1 one = ONE()
      2 eid = one.search(lab='wittenlab', date='2019-08-04')
----> 3 datasets = one.load(eid, download_only=True)
      4 ses_path = datasets[0].local_path.parent  # local path where the data has been downloaded

~\Anaconda3\envs\ibllib\lib\site-packages\oneibl\one.py in load(self, eid, dataset_types, dclass_output, dry_run, cache_dir, download_only, clobber, offline, keep_uuid)
    218         return self._load_recursive(eid, dataset_types=dataset_types, dclass_output=dclass_output,
    219                                     dry_run=dry_run, cache_dir=cache_dir, keep_uuid=keep_uuid,
--> 220                                     download_only=download_only, clobber=clobber, offline=offline)
    221
    222     def _load_recursive(self, eid, **kwargs):

~\Anaconda3\envs\ibllib\lib\site-packages\oneibl\one.py in _load_recursive(self, eid, **kwargs)
    238                 out = []
    239                 for e in eid:
--> 240                     out.append(self._load(e, **kwargs)[0])
    241             return out
    242

~\Anaconda3\envs\ibllib\lib\site-packages\oneibl\dataclass.py in __getitem__(self, ind)
     28     def __getitem__(self, ind):
     29         return SessionDataInfo(
---> 30             dataset_type=self.dataset_type[ind],
     31             dataset_id=self.dataset_id[ind],
     32             local_path=self.local_path[ind],

IndexError: list index out of range``` 

when trying to use `ax = bbp.peri_event_time_histogram(spikes.times, spikes.clusters, trials.goCue_times, 121)` (with any cluster I try) I get this warning: ```C:\Users\chris\Anaconda3\envs\ibllib\lib\site-packages\brainbox\singlecell\singlecell.py:81: RuntimeWarning: invalid value encountered in greater_equal
  idxs = np.bitwise_and(spike_times >= np.min(align_times) - (n_bins_pre + 1) * bin_size,
C:\Users\chris\Anaconda3\envs\ibllib\lib\site-packages\brainbox\singlecell\singlecell.py:82: RuntimeWarning: invalid value encountered in less_equal
  spike_times <= np.max(align_times) + (n_bins_post + 1) * bin_size)
C:\Users\chris\Anaconda3\envs\ibllib\lib\site-packages\brainbox\plot\plot.py:534: UserWarning: Attempting to set identical bottom == top == 0.0 results in singular transformations; automatically expanding.
  ax.set_ylim([-plot_edge if include_raster else 0., plot_edge])``` with a flat peth figure as output

**Comment by berkgercek** [comment]
Hey Chris,

This is breaking because there are `NaN` values in the align times you're providing to the plot function. I've encountered this error myself too in trying to replicate with a different session. You need to filter out NaN values in the goCue_times variable you're passing to the function.

I'll modify the function to filter for those internally and throw a more informative warning in the future!
