### ISSUE TITLE
ONE.load_object() returns path

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#139]
**Describe the bug**
Instead of returning all data, ONE.load_object returns a WindowsPath obj for one of the sessions.  This doesn't happen for all sessions.  The problem arises from `_load`.

**To Reproduce**
```
eid = '2d5f6d81-38c4-4bdc-ac3c-302ea4d5f46e'  # CSHL047/2020-01-22/002/
wheel = one.load_object(eid, 'wheel')

# Print value types
[print(k + ' is a ' + wheel[k].__class__.__name__) for k in wheel]

position is a ndarray
timestamps is a WindowsPath
velocity is a ndarray
```

**Expected behavior**
In the above example the timestamps ALF exists for that session so should be loaded and returned.

**Additional context**
ibllib 1.4.11

**Comment by k1o0** [comment]
It seems this is a 'feature' not a bug, although I would prefer it to raise an exception rather than just return a path.  `check_dimensions` is unhelpful because it completely ignores the timestamps file (granted, it would anyway because it's not an ndarray).  Something like this would be more useful:

```
excluded_attributes = list()
# If timestamps are 1D check dimensions against other attributes
if 'timestamps' in dico.keys() and len(dico['timestamps'].shape) != 1:
    excluded_attributes.append('timestamps')
```

FYI The timestamps file is downloaded and is empty for some reason.

**Comment by nbonacchi** [comment]
Works here, can't reproduce:

```
eid = '2d5f6d81-38c4-4bdc-ac3c-302ea4d5f46e'  # CSHL047/2020-01-22/002/ 
    wheel = one.load_object(eid, 'wheel') 
     
    # Print value types 
    [print(k + ' is a ' + wheel[k].__class__.__name__) for k in wheel]

position is a ndarray
timestamps is a ndarray
velocity is a ndarray

wheel                                                                                                                                                        
{'position': array([ 1.53398079e-03, -0.00000000e+00, -1.53398079e-03, ...,
         5.44274791e+02,  5.44276325e+02,  5.44274791e+02]),
 'timestamps': array([5.13333333e-03, 9.40000000e-03, 1.34333333e-02, ...,
        4.43210833e+03, 4.43268777e+03, 4.43303973e+03]),
 'velocity': array([-0.34883486, -0.37021864, -0.38354846, ...,  0.00943495,
        -0.00171093, -0.00700569])}
```

**Comment by oliche** [comment]
Miles, try to clean up the offending file by running once the code with
`clobber=True`
What is happening here is you have a corrupt file in your cache that
doesn't get overwritten.

The next release of ONE handles this by redownloading datasets if either
the checksum or the filesize don't match what is on the flatiron.

**Comment by k1o0** [comment]
With clobber I get the following Windows error:
```
  File "C:\Users\Miles\Anaconda3\lib\pathlib.py", line 1312, in rename
    self._accessor.rename(self, target)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Miles\\Downloads\\FlatIron\\churchlandlab\\Subjects\\CSHL047\\2020-01-22\\002\\alf\\_ibl_wheel.timestamps.db45be84-6bcd-479d-980c-edc22a5ad4a6.npy' -> 'C:\\Users\\Miles\\Downloads\\FlatIron\\churchlandlab\\Subjects\\CSHL047\\2020-01-22\\002\\alf\\_ibl_wheel.timestamps.npy'
```
