### ISSUE TITLE
Clearer names for camera DataSessionInfo

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#142]
**Is your feature request related to a problem? Please describe.**
When loading camera data there is no clear way to determine the order.  For example:
```
cam_ts = one.load(eid, ['camera.times'])
type(cam_ts)  # <class 'list'>
```
I might assume this is in alphabetical order (i.e. `[bodyCamera, leftCamera, rightCamera]`) but judging by the size, one of the side cameras is first in the list.  Normally loading by object would provide a solution but that requires loading all frames into memory.  

The `dclass_output` flag is sub-optimal because the only way to determine the ALF attribute is to process the url strings:
```
cam_ts = one.load(eid, ['camera.times'], dclass_output=True)
print(cam_ts.dataset_type)  # ['camera.times', 'camera.times', 'camera.times']
```

ONE refuses to recognize the precise ALF names
```
one.load(eid, ['leftCamera.times'])  # :(
```

**Describe the solution you'd like**
I suppose the best solution would be to return a dataset_type list with more informative names, like `['bodyCamera.times', 'leftCamera.times', 'rightCamera.times']`.  It might also be worth allowing users to call load with e.g. `leftCamera.times`.

**Comment by nbonacchi** [comment]
This a more general problem with the collections, if more than one dstype is registered with the same name, there is no way of:
1. just querying if one of the datasets exists, both in one.search() and one.load() as stated
2. when returning multiple 'instances' of the datasetType there is no clear order or way of distinguishing them, or better still in case the data is large only downloading one of them e.g. one.load(eid, 'spikes.times' <only for probe_label==001>)

maybe we should return a bunch with the name of the collection {'probe01': spike.times array, 'probe00': spike.times array} 

This could also be useful in general for the output of one.load, it would simplify the output as is would be always a Bunch or a dict, and be more explicit. Right now this could happen: 
names, some = one.load(eid, dataset_types=['some', 'names'])

Whether the file names are the same but in a different path like spike,times OR the file names are in the same folder but with different names leftCametra, rightCamera, etc, using the relative path (or full path)  should help disambiguate whatis what.

**Comment by rossant** [comment]
Closing as part of the ONE v2 discussion
