### ISSUE TITLE
Brainbox function request : plot waveform of spikes along channel location

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/ibllib#153]
For a given cluster, and for all channels on the probe (or subset* of channels), plot its spike waveform at the location of the channel.

Subset could be either N channels near the channel with the max PTP amplitude, or M channels with significant amplitude (>3 above noise STD or so).

Waveform could be mean waveform, mean+s.t.d., or subset (n, uniformly sampled?) of raw waveforms.

**Comment by jaib1** [comment]
do you want this function to extract waveforms also, or just plot waveforms given a waveforms array of [#spikes X #channels X #samples] ?

check out `brainbox.io.extract_waveforms` (I should probably clean this up to use the spikeglx code, or alternatively just use the phylib extract waveforms function).

this output could then just be plotted where you create an axes for each channel, if you wanted to do something like this.

n.b. matplotlib is poor at handling many line objects, so doing something with matplotlib like plotting a few hundred waveforms over 20+ channels is not going to work well..

**Comment by GaelleChapuis** [comment]
I think the latter:  just plot waveforms given a waveforms array of [#spikes X #channels X #samples]

**Comment by nsteinme** [comment]
I think we had in mind primarily plotting mean or template waveforms, not
hundreds of waveforms, though that could be a useful version too!

In matlab you can do a trick where you connect many vectors that are to be
plotted as lines together with NaN's which allows just making one line
object, i.e. these make the same thing:

plot([1 2 NaN 3 4], [1 1 NaN 2 2]);

and

plot([1 2], [1 1]); hold on; plot([3 4], [2 2]);

maybe something similar in matplotlib?

**Comment by oliche** [comment]
I missed the discussion on Thursday but there has been already functions for this in ibllib.plots for a year or so. I was looking at waveforms again recently and did some local changes, I'll push them tomorrow.

**Comment by oliche** [comment]
This is what I had for personal use so far to look at wavelets.
No need to overlay the density with the traces, they can be separate.

A feature I thought useful was the callbacks ctrl+A and ctrl+Z to respectively increase and decrease the gain by 3dB.

![Figure_1](https://user-images.githubusercontent.com/15081095/79733011-64028180-82ec-11ea-8b37-baeb3956a575.png)

```
from ibllib.plots import Density, Traces
import alf.io
ppath = '/datadisk/FlatIron/churchlandlab/Subjects/CSHL045/2020-02-26/001/alf/probe00'

channels = alf.io.load_object(ppath, 'channels')
it = 255
ordre = np.argsort(templates.waveformsChannels[it, :])

d = Density(templates.waveforms[it, :, ordre].transpose(), fs=30000)
t = Traces(templates.waveforms[it, :, ordre].transpose(), fs=30000, ax=d.ax)
```
