### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kdharris101** [int-brain-lab/ibllib#16]
Hi there,

I guess I need to reinstall to get the new version working. (Just cloning it didn't make a difference.)

But I have had a problem with installation. Maybe I just did something dumb. But there seems to be a problem that it has doubled the Cache directory.

Full dump (including installation) below:

(base) A:\git\ibllib\python>python setup.py install
Enter the URL of Alyx Instance [https://test.alyx.internationalbrainlab.org]:
https://test.alyx.internationalbrainlab.org
Enter Alyx username [test_user]:
test_user
Enter the Alyx password for test_user:
Enter the Alyx password (again):
Directory to cache FlatIron downloads [C:\Users\Kenneth\Downloads\FlatIron]:A:\ONEcache
A:\ONEcache
Enter the FlatIron username [iblmember]:
iblmember
Enter the FlatIron password:
Enter the FlatIron password (again):
running install
running bdist_egg
running egg_info
writing ibllib.egg-info\PKG-INFO
writing dependency_links to ibllib.egg-info\dependency_links.txt
writing requirements to ibllib.egg-info\requires.txt
writing top-level names to ibllib.egg-info\top_level.txt
reading manifest file 'ibllib.egg-info\SOURCES.txt'
writing manifest file 'ibllib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying oneibl\params.py -> build\lib\oneibl
copying oneibl\params_secret.py -> build\lib\oneibl
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\alf
copying build\lib\alf\extractors.py -> build\bdist.win-amd64\egg\alf
copying build\lib\alf\scraper.py -> build\bdist.win-amd64\egg\alf
copying build\lib\alf\__init__.py -> build\bdist.win-amd64\egg\alf
creating build\bdist.win-amd64\egg\ibllib
creating build\bdist.win-amd64\egg\ibllib\dsp
copying build\lib\ibllib\dsp\savitzky_golay.py -> build\bdist.win-amd64\egg\ibllib\dsp
copying build\lib\ibllib\dsp\smooth.py -> build\bdist.win-amd64\egg\ibllib\dsp
copying build\lib\ibllib\dsp\__init__.py -> build\bdist.win-amd64\egg\ibllib\dsp
creating build\bdist.win-amd64\egg\ibllib\io
copying build\lib\ibllib\io\raw_data_loaders.py -> build\bdist.win-amd64\egg\ibllib\io
copying build\lib\ibllib\io\__init__.py -> build\bdist.win-amd64\egg\ibllib\io
creating build\bdist.win-amd64\egg\ibllib\misc
copying build\lib\ibllib\misc\flatten.py -> build\bdist.win-amd64\egg\ibllib\misc
copying build\lib\ibllib\misc\misc.py -> build\bdist.win-amd64\egg\ibllib\misc
copying build\lib\ibllib\misc\timing.py -> build\bdist.win-amd64\egg\ibllib\misc
copying build\lib\ibllib\misc\__init__.py -> build\bdist.win-amd64\egg\ibllib\misc
copying build\lib\ibllib\time.py -> build\bdist.win-amd64\egg\ibllib
copying build\lib\ibllib\webclient.py -> build\bdist.win-amd64\egg\ibllib
copying build\lib\ibllib\__init__.py -> build\bdist.win-amd64\egg\ibllib
creating build\bdist.win-amd64\egg\oneibl
creating build\bdist.win-amd64\egg\oneibl\examples
copying build\lib\oneibl\examples\tutorial_script.py -> build\bdist.win-amd64\egg\oneibl\examples
copying build\lib\oneibl\examples\__init__.py -> build\bdist.win-amd64\egg\oneibl\examples
copying build\lib\oneibl\one.py -> build\bdist.win-amd64\egg\oneibl
copying build\lib\oneibl\params.py -> build\bdist.win-amd64\egg\oneibl
copying build\lib\oneibl\params_secret.py -> build\bdist.win-amd64\egg\oneibl
copying build\lib\oneibl\params_secret_template.py -> build\bdist.win-amd64\egg\oneibl
copying build\lib\oneibl\__init__.py -> build\bdist.win-amd64\egg\oneibl
byte-compiling build\bdist.win-amd64\egg\alf\extractors.py to extractors.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\alf\scraper.py to scraper.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\alf\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\dsp\savitzky_golay.py to savitzky_golay.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\dsp\smooth.py to smooth.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\dsp\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\io\raw_data_loaders.py to raw_data_loaders.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\io\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\misc\flatten.py to flatten.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\misc\misc.py to misc.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\misc\timing.py to timing.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\misc\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\time.py to time.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\webclient.py to webclient.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\ibllib\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\oneibl\examples\tutorial_script.py to tutorial_script.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\oneibl\examples\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\oneibl\one.py to one.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\oneibl\params.py to params.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\oneibl\params_secret.py to params_secret.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\oneibl\params_secret_template.py to params_secret_template.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\oneibl\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying ibllib.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying ibllib.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ibllib.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ibllib.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ibllib.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\ibllib-0.1.2-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing ibllib-0.1.2-py3.6.egg
Removing a:\anaconda3\lib\site-packages\ibllib-0.1.2-py3.6.egg
Copying ibllib-0.1.2-py3.6.egg to a:\anaconda3\lib\site-packages
ibllib 0.1.2 is already the active version in easy-install.pth

Installed a:\anaconda3\lib\site-packages\ibllib-0.1.2-py3.6.egg
Processing dependencies for ibllib==0.1.2
Searching for requests==2.14.2
Best match: requests 2.14.2
Adding requests 2.14.2 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for pandas==0.20.2
Best match: pandas 0.20.2
Adding pandas 0.20.2 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for numpy==1.12.1
Best match: numpy 1.12.1
Adding numpy 1.12.1 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for matplotlib==2.2.2
Best match: matplotlib 2.2.2
Adding matplotlib 2.2.2 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for dataclasses==0.6
Best match: dataclasses 0.6
Adding dataclasses 0.6 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for pytz==2017.2
Best match: pytz 2017.2
Adding pytz 2017.2 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for python-dateutil==2.6.0
Best match: python-dateutil 2.6.0
Adding python-dateutil 2.6.0 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for kiwisolver==1.0.1
Best match: kiwisolver 1.0.1
Adding kiwisolver 1.0.1 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for pyparsing==2.1.4
Best match: pyparsing 2.1.4
Adding pyparsing 2.1.4 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using a:\anaconda3\lib\site-packages
Searching for setuptools==27.2.0
Best match: setuptools 27.2.0
Processing setuptools-27.2.0-py3.6.egg
setuptools 27.2.0 is already the active version in easy-install.pth
Installing easy_install-script.py script to A:\Anaconda3\Scripts
Installing easy_install.exe script to A:\Anaconda3\Scripts
Installing easy_install-3.6-script.py script to A:\Anaconda3\Scripts
Installing easy_install-3.6.exe script to A:\Anaconda3\Scripts

Using a:\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg
Finished processing dependencies for ibllib==0.1.2

(base) A:\git\ibllib\python>run_tests

(base) A:\git\ibllib\python>cd .\ibllib\tests

(base) A:\git\ibllib\python\ibllib\tests>python -m unittest discover
.Downloading: C:\Users\Kenneth\AppData\Local\Temp\tmphp1n85gh\clusters._phy_annotation.6f3eb5f5-f6e8-4c1a-80e5-88e127a80893.npy Bytes: 8952
      8952  [100.00%]
...
----------------------------------------------------------------------
Ran 4 tests in 0.853s

OK

(base) A:\git\ibllib\python\ibllib\tests>cd ..\..\oneibl\tests

(base) A:\git\ibllib\python\oneibl\tests>python -m unittest discover
[
    "86e27228-8708-48d8-96ed-9aa61ab951db"
]
data    : <class 'list'> , 29 items = []
dataset_id    : <class 'list'> , 29 items = 80930c88-0c93-41db-977f-40adcff66df2
local_path    : <class 'list'> , 29 items =
dataset_type    : <class 'list'> , 29 items = unknown
url    : <class 'list'> , 29 items = http://ibl.flatironinstitute.org/mainenlab/Subjects/clns0730/2018-08-24/1/_ibl_wheel.timestamps.80930c88-0c93-41db-977f-40a
dcff66df2.npy
eid    : <class 'list'> , 29 items = 86e27228-8708-48d8-96ed-9aa61ab951db

data    : <class 'list'> , 29 items = []
dataset_id    : <class 'list'> , 29 items = 80930c88-0c93-41db-977f-40adcff66df2
local_path    : <class 'list'> , 29 items =
dataset_type    : <class 'list'> , 29 items = unknown
url    : <class 'list'> , 29 items = http://ibl.flatironinstitute.org/mainenlab/Subjects/clns0730/2018-08-24/1/_ibl_wheel.timestamps.80930c88-0c93-41db-977f-40a
dcff66df2.npy
eid    : <class 'list'> , 29 items = 86e27228-8708-48d8-96ed-9aa61ab951db

subject :  clns0730
users :  ['olivier']
lab :  None
type :  Base
start_time :  2018-08-24T12:34:56
end_time :  2018-08-24T12:34:57
subject :  ['clns0730', 'flowers']
users :  [['olivier'], ['olivier']]
lab :  [None, None]
type :  ['Base', 'Base']
start_time :  ['2018-08-24T12:34:56', '2018-07-13T12:34:56']
end_time :  ['2018-08-24T12:34:57', '2018-07-13T12:34:57']
..EE.....E
======================================================================
ERROR: test_load (test_one.TestLoad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "A:\git\ibllib\python\oneibl\tests\test_one.py", line 47, in test_load
    t, cr, cl = myone.load(eid, dataset_types=dataset_types)
  File "A:\Anaconda3\lib\site-packages\ibllib-0.1.2-py3.6.egg\oneibl\one.py", line 174, in load
    cache_dir = _cache_directory(par.CACHE_DIR, ses)
  File "A:\Anaconda3\lib\site-packages\ibllib-0.1.2-py3.6.egg\oneibl\one.py", line 20, in _cache_directory
    pathlib.Path(cache_dir).mkdir(parents=True, exist_ok=True)
  File "A:\Anaconda3\lib\pathlib.py", line 1233, in mkdir
    self._accessor.mkdir(self, mode)
  File "A:\Anaconda3\lib\pathlib.py", line 390, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'A:\\ONEcache\\A:\\ONEcacheclns0730\\2018-08-24\\1'

======================================================================
ERROR: test_load_all_data_available (test_one.TestLoad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "A:\git\ibllib\python\oneibl\tests\test_one.py", line 77, in test_load_all_data_available
    a = myone.load(eid)
  File "A:\Anaconda3\lib\site-packages\ibllib-0.1.2-py3.6.egg\oneibl\one.py", line 174, in load
    cache_dir = _cache_directory(par.CACHE_DIR, ses)
  File "A:\Anaconda3\lib\site-packages\ibllib-0.1.2-py3.6.egg\oneibl\one.py", line 20, in _cache_directory
    pathlib.Path(cache_dir).mkdir(parents=True, exist_ok=True)
  File "A:\Anaconda3\lib\pathlib.py", line 1233, in mkdir
    self._accessor.mkdir(self, mode)
  File "A:\Anaconda3\lib\pathlib.py", line 390, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'A:\\ONEcache\\A:\\ONEcacheflowers\\2018-07-13\\1'

======================================================================
ERROR: test_one_tutorial (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_one_tutorial
Traceback (most recent call last):
  File "A:\Anaconda3\lib\unittest\loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "A:\Anaconda3\lib\unittest\loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "A:\git\ibllib\python\oneibl\tests\test_one_tutorial.py", line 1, in <module>
    import oneibl.examples.tutorial_script
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "A:\Anaconda3\lib\site-packages\ibllib-0.1.2-py3.6.egg\oneibl\examples\tutorial_script.py", line 31, in <module>
    wf, pr, d = one.load(eid, dataset_types=dataset_types)
  File "A:\Anaconda3\lib\site-packages\ibllib-0.1.2-py3.6.egg\oneibl\one.py", line 174, in load
    cache_dir = _cache_directory(par.CACHE_DIR, ses)
  File "A:\Anaconda3\lib\site-packages\ibllib-0.1.2-py3.6.egg\oneibl\one.py", line 20, in _cache_directory
    pathlib.Path(cache_dir).mkdir(parents=True, exist_ok=True)
  File "A:\Anaconda3\lib\pathlib.py", line 1233, in mkdir
    self._accessor.mkdir(self, mode)
  File "A:\Anaconda3\lib\pathlib.py", line 390, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'A:\\ONEcache\\A:\\ONEcacheclns0730\\2018-08-24\\1'

----------------------------------------------------------------------
Ran 10 tests in 5.671s

FAILED (errors=3)

(base) A:\git\ibllib\python\oneibl\tests>

**Comment by kdharris101** [comment]
Think I found the problem: line 18 of one.py should be 

`cache_dir += os.sep +  ses['subject'] + os.sep + ses['start_time'][0:10]`

I couldn't figure out how to make a pull request though!

**Comment by oliche** [comment]
Yes absolutely. This was not caught on Linux since concatenated paths are valid.
It is fixed on master and dev, I just did a hotfix, so if you repeat the install procedure (or git clone) this will be fixed.

I will probably get a Windows laptop to avoid shipping like this in the future.
