### ISSUE TITLE
clobber=False isn't working for one.load with cortex lab data

### ISSUE THREAD

**Issue by mayofaulkner** [int-brain-lab/ibllib#179]
**Describe the bug**

For cortexlab data the `clobber=False` option doesn't seem to work. `one.load` re-downloads the data from FlatIron even when the data has already been downloaded and is present in the correct directory. This problem does not occur for mainenlab, churchlandlab or mrsicflogellab data (I haven't checked other labs)

**To Reproduce**
```
# cortex lab eid
eid = `a3df91c8-52a6-4afa-957b-3479a7d0897c`
# First time downloads file as expected
_ = one.load(eid, dataset_types='spikes.amps')

# downloads again despite file being downloaded
_ = one.load(eid, dataset_types='spikes.amps', clobber=False)


# churchland lab eid
eid = 'a71175be-d1fd-47a3-aa93-b830ea3634a1'
# First time downloads file as expected
_ = one.load(eid, dataset_types='spikes.amps')

# this time doesn't download file
_ = one.load(eid, dataset_types='spikes.amps', clobber=False)

```

**Additional context**
First noticed the problem this week. Last week was having no problems and behaved as expected

**Comment by oliche** [comment]
@anne-urai #193

**Comment by anne-urai** [comment]
Correct, this seems to just happen for cortexlab (but have not tried extensively).

**Comment by oliche** [comment]
Fized by re-transferring datasets for cortexlab patched data.
There are still cases where patching cortexlab data results in a failed transfer.
