### ISSUE TITLE
Problem with MATLAB version

### ISSUE THREAD

**Issue by kdharris101** [int-brain-lab/ibllib#18]
I haven't been able to get the MATLAB version to install. When I run `AlyxClient.setup()` it doesn't ask for username or password for the flatiron server. Then it gives an error accessing it. 

Is there a specific branch I should be trying?

**Comment by oliche** [comment]
I should have warned you that the doc is not updated yet !

The Matlab and Python parameters now point to the same file so users can switch back and forth.
The Python setup.py does not prompt anymore for params so the library can be installed via pip as a dependency for the IBLrig code.

For the full setup with ONE, I've just pushed a static method setup.
So on the feature/matlab branch: `git pull`

An then in Matlab:

    myone = one;
You should be prompted for parameters. If you want to explicitly change parameters you can use this static method:

    one.setup;

There is only one feature of list missing compared to Python.
The Matlab unit test for one is a good example of available features.

**Comment by oliche** [comment]
NB: I don't have Windows here so it's untested yet.
The good news is I have received my stuff today and I will be able to unearth an old Windows computer to test.

**Comment by kdharris101** [comment]
I’m finding a few bugs with myone.setup in MATLAB.

One on line 55 of one.m: it should be `par=setup(self)`. But I think there are others too. Have you debugged this function yet?

**Comment by oliche** [comment]
Yes it seems you're not on the same branch/commit as me as I have setup() as a static function line 58, which doesn't require a self argument.
The release is imminent, you'll probably waste less time with proper documentation. Sorry.
