### ISSUE TITLE
Inferring wheel encoding fails for bpod

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#180]
**Describe the bug**
The wheelMoves extractor attempts to determine the encoding by looking at the diff of the wheel trace.  This fails as some diffs between samples are 0, some are very large due to resets.  A test for this should be added to the QC, and the extractor should simple hard-code the encoding value as this affects the algorithm's performance.

Finding the median diff is probably the most reliable why to infer the encoding.

**To Reproduce**
```
# Example of zero diff between samples
eid = '150f92bc-e755-4f54-96c1-84e1eaf832b4'
sess_path = one.path_from_eid(eid)
ts, pos = get_wheel_position(sess_path)
print (np.abs(np.ediff1d(pos)).min())
```

**Comment by oliche** [comment]
@k1o0 I suppose this is fixed right ?

**Comment by k1o0** [comment]
Yes
