### ISSUE TITLE
required_datasets extractor class attribute

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#187]
**Is your feature request related to a problem? Please describe.**
I'm re-extracting a lot nowadays and although this isn't 'user facing' code, I suspect others will want to locally extract data in the future.  The extractors can partially run and fail when there is missing local data and it's difficult to know in advance what files are required for each extractor.

**Describe the solution you'd like**
In addition to the `save_names` and `var_names` attributes, add a third called `required_datasets` which is a tuple of dataset types required for the extractor to run.  This can be accessed without instantiating the class, which is useful for locally downloading the files via ONE before running the extractor.  Additionally the base class could assert that these files exist locally during init.  This makes the process much less opaque and is east to implement.

**Comment by oliche** [comment]
Absolutely, we even wanted to have expected outputs as the property for the jobs.
What stumped me (and I didn't think too hard to be honest) is the fact that

- some datasets are required, other are optional
- for a same task, some datasets are required in some context but not in another context
- some datasets have multiple instances in some contexts (multiple probes, multiple cameras)

I don't think this should prevent you from trying, as you said, it seems pretty inoccuous to me and is a good way to document the code.

**Comment by k1o0** [comment]
Good point, I will close this for now.
