### ISSUE TITLE
launch_phy downloads data each time

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/ibllib#193]
When running `launch_phy` with the same dataset multiple times, the data are downloaded each time. This is not a problem, but causes a bit of a delay.  
Could the download settings be changed (presumably https://github.com/int-brain-lab/iblapps/blob/develop/launch_phy/phy_launcher.py#L52) so that existing data is not re-downloaded each time?

**Comment by oliche** [comment]
duplicate #179
