### ISSUE TITLE
unable to read into ephys.raw.lf/ap/nidq dataset using spikeglx

### ISSUE THREAD

**Issue by Saksham20** [int-brain-lab/ibllib#206]
Unable to read ephys.raw.lf/ap/nidq datasets using spikeglx.Reader()

**To Reproduce**
```python
from oneibl.one import ONE
from ibllib.io import spikeglx
one=ONE()
eid_raw_data='db4df448-e449-4a6f-a0e7-288711e7a75a'
ephysData_raw_ap = one.load(eid_raw_data,dataset_types=['ephysData.raw.nidq'])
# ephysData_raw_nidq is a list of WindowsPath to the file location on my HDD, i locate the file and use path as argument
ap_data = spikeglx.Reader(r"E:\FlatIron\danlab\Subjects\DY_009\2020-02-27\001\raw_ephys_data\_spikeglx_ephysData_g0_t0.nidq.cbin")
```
**Error**:
```
Traceback (most recent call last):
  File "~\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-f8edf4fab8bd>", line 1, in <module>
    sr = spikeglx.Reader(r"E:\FlatIron\danlab\Subjects\DY_009\2020-02-27\001\raw_ephys_data\_spikeglx_ephysData_g0_t0.nidq.cbin")
  File "~\venv\lib\site-packages\ibllib\io\spikeglx.py", line 41, in __init__
    self._raw.open(self.file_bin, self.file_bin.with_suffix('.ch'))
  File "~\venv\lib\site-packages\mtscomp.py", line 543, in open
    with open(cmeta, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\FlatIron\\danlab\\Subjects\\DY_009\\2020-02-27\\001\\raw_ephys_data\\_spikeglx_ephysData_g0_t0.nidq.ch'
```
**Expected behavior**
Based on this [document](https://docs.google.com/document/d/1OqIqqakPakHXRAwceYLwFY9gOrm8_P62XIfCTnHwstg/edit#heading=h.ms0y69xbzova) page 19  I want to be able to index into the dataset:
```Python
from ibllib.io import spikeglx
ap_file = "/path/to/my/_spikeglx_ephysData_g0_t0.imec1.ap.cbin"
sr = spikeglx.Reader(ap_file)
dat = sr.read(0:10000) 
```

**Desktop**
 - OS: Windows 7

**Comment by oliche** [comment]
We use compression to store the binary data (https://github.com/int-brain-lab/mtscomp)
So you need 3 files to properly read spikeglx:

- the binary data itself:  `_spikeglx_ephysData_g0_t0.nidq.cbin`
- the meta data file:  `_spikeglx_ephysData_g0_t0.nidq.meta`
- a compression indexing file `_spikeglx_ephysData_g0_t0.nidq.ch` `_spikeglx_ephysData_g0_t0.nidq.ch`

In this case, you are missing the latter and just need to download it.

Also, in the latest version of spikeglx, you can slice the reader as if it was a numpy array. For example to get the first thousand samples:
`dat = sr[0:1000, :]`

I've updated the document you've listed with all those indications.
Feel free to re-open if you have further issues

**Comment by Saksham20** [comment]
when I try to explicitly download the file like: 
```python
ch = one.load(eid_raw_data,dataset_types=['ephysData.raw.ch'])
meta = one.load(eid_raw_data,dataset_types=['ephysData.raw.meta'])
```
#### Expected result:
- As expected: **meta** I get three *.meta files as` _spikeglx_ephysData_g0_t0.nidq.meta`, `_spikeglx_ephysData_g0_t0.imec0.ap.meta`, `_spikeglx_ephysData_g0_t0.imec0.lf.meta` corresponding to the cbin files of `nidq,` `ap` and `lf.` 
- Not as expected: **ch** I get only two files: `spikeglx_ephysData_g0_t0.imec0.ap.ch,` `_spikeglx_ephysData_g0_t0.imec0.lf.ch` for cbin of `ap` and `lf` but missing for `nidq` 

So, now using `spikeglx` to read into these files works but not for nidq due to its missing ch file

**Comment by oliche** [comment]
Ok what is  the value of eid_raw_data ?

**Comment by Saksham20** [comment]
```
eid_raw_data='db4df448-e449-4a6f-a0e7-288711e7a75a' 

eid_multiple_probes='da188f2c-553c-4e04-879b-c9ea2d1b9a93'
```

I tried for these eids
