### ISSUE TITLE
unable to load parquet files in windows machines

### ISSUE THREAD

**Issue by Saksham20** [int-brain-lab/ibllib#209]
**Problem**
I am trying to access `camera.dlc `dataset: 
```python
eid_camera_dlc = one.search(dataset_types=['camera.dlc'])[0]
cam_dlc = one.load(eid_camera_dlc, dataset_types=['camera.dlc'])
# cam_dlc is a list of paths of filetype .pqt
```
I use the Apache pyarrow reader to read this like so: 
```python
import pyarrow.parquet as pq
dlc_data = pq.read_table(cam_dlc[0])
```

**Result : python crash:**

![image](https://user-images.githubusercontent.com/11567561/93275147-bd7ab980-f781-11ea-946f-49366d083563.png)

I tried creating a dummy `.pqt` and read that just fine using the `pyarrow.parquet`, so i dont suspect there could be some error on my end. Is there an alternate reader you recommend? 

I'm not sure but this internally may have the same reason for this issue: int-brain-lab/iblenv#40

**Comment by mayofaulkner** [comment]
Using, `cam_dlc = one.load(eid_camera_dlc, dataset_types=['camera.dlc'])` returns a list of the actual dlc data not the paths to the data. For example `type(cam_dlc[0])` returns `pandas.core.frame.DataFrame`. 

To get access to the paths and then use `pyarrow.parquet` to read in the `.pqt` files you can use the `download_only` option. 
```
cam_dlc_path = one.load(eid_camera_dlc, dataset_types=['camera.dlc'], download_only=True)
type(cam_dlc_path[0])
--> pathlib.WindowsPath

import pyarrow.parquet as pq
cam_dlc = pq.read_table(cam_dlc_path[0])
```

I will close the issue but feel free to reopen if you run into other problems or have any other questions!

**Comment by Saksham20** [comment]
Thanks @mayofaulkner but the problem seems to lie in windows machines( I have tried on Windows 10/7) based on this open issue on Apache https://issues.apache.org/jira/browse/ARROW-8385 #
this is why instantiating a one class crashes python  int-brain-lab/iblenv#40 as well. 

I guess you're using linux?

**Comment by mayofaulkner** [comment]
I am also on Windows and haven't had any problems with loading the `.pqt` file nor instantiating `one=ONE()`. I am on Windows 10 and have python 3.7.9 (64bit version installed). My environment contains the following packages
```
Package             Version
------------------- -------------------
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.2.0
backcall            0.2.0
bleach              3.2.0
certifi             2020.6.20
cffi                1.14.2
chardet             3.0.4
click               7.1.2
colorama            0.4.3
colorlog            4.2.1
cryptography        3.1
cycler              0.10.0
dask                2.26.0
decorator           4.4.2
defusedxml          0.6.0
entrypoints         0.3
flake8              3.8.3
globus-sdk          1.9.1
graphviz            0.14.1
ibllib              1.5.11
idna                2.10
importlib-metadata  1.7.0
ipykernel           5.3.4
ipython             7.18.1
ipython-genutils    0.2.0
ipywidgets          7.5.1
jedi                0.17.2
Jinja2              2.11.2
joblib              0.16.0
json5               0.9.5
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.7
jupyter-console     6.2.0
jupyter-core        4.6.3
jupyterlab          2.2.8
jupyterlab-pygments 0.1.1
jupyterlab-server   1.2.0
kiwisolver          1.2.0
llvmlite            0.34.0
MarkupSafe          1.1.1
matplotlib          3.3.2
mccabe              0.6.1
mistune             0.8.4
mtscomp             1.0.1
nbclient            0.5.0
nbconvert           6.0.2
nbformat            5.0.7
nest-asyncio        1.4.0
notebook            6.1.4
numba               0.51.2
numpy               1.19.2
opencv-python       4.4.0.42
packaging           20.4
pandas              1.1.2
pandocfilters       1.4.2
parso               0.7.1
phylib              2.2
pickleshare         0.7.5
Pillow              7.2.0
pip                 20.2.2
prometheus-client   0.8.0
prompt-toolkit      3.0.7
pyarrow             1.0.1
pycodestyle         2.6.0
pycparser           2.20
pyflakes            2.2.0
Pygments            2.7.0
PyJWT               1.7.1
pynrrd              0.4.2
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
pytz                2020.1
pywin32             228
pywinpty            0.5.7
PyYAML              5.3.1
pyzmq               19.0.2
qtconsole           4.7.7
QtPy                1.9.0
requests            2.24.0
scikit-learn        0.23.2
scipy               1.5.2
seaborn             0.11.0
Send2Trash          1.5.0
setuptools          49.6.0.post20200814
six                 1.15.0
terminado           0.8.3
testpath            0.4.4
threadpoolctl       2.1.0
toolz               0.10.0
tornado             6.0.4
tqdm                4.49.0
traitlets           5.0.4
urllib3             1.25.10
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.35.1
widgetsnbextension  3.5.1
wincertstore        0.2
zipp                3.1.0
```

**Comment by Saksham20** [comment]
is this a conda env?

**Comment by mayofaulkner** [comment]
yes, i just made a clean conda env environment and then installed ibllib
```
conda create --no-default-packages -n parquet_env python=3.7
pip install ibllib
```

**Comment by oliche** [comment]
@Saksham20 could you please post the output of 
`conda version`
and `conda list` ?

**Comment by Saksham20** [comment]
after following the steps like @mayofaulkner 
here is my conda_env.yaml file:
[ibl_env.txt](https://github.com/int-brain-lab/ibllib/files/5235280/ibl_env.txt)

**Comment by mayofaulkner** [comment]
Through pypi
`pyarrow                   1.0.1                    pypi_0    pypi`

Attached is my conda_env.yaml 
[pq_testing.txt](https://github.com/int-brain-lab/ibllib/files/5237384/pq_testing.txt)

What version of conda are you using? I am conda 4.8.1

**Comment by Saksham20** [comment]
my conda version is **4.8.5.**
Its still mysterious why it works on your windows machine but not on mine. 
 
But, i've got it to work finally by installing pyarrow from **conda-forge instead of pypi**. 
pyarrow: version 1.01, channel: conda-forge. On the open [apache issue ](https://issues.apache.org/jira/browse/ARROW-8385), some said [pyarrow was fixed on conda-forge](https://issues.apache.org/jira/browse/ARROW-7939?focusedCommentId=17147132&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17147132)

so, @mayofaulkner I updated your method to create the environment like so:
```
conda create --no-default-packages -n parquet_env python=3.7
pip install ibllib
conda install -c conda-forge pyarrow=1.0.1
```

I think it would be useful if this [iblenv list](https://github.com/int-brain-lab/iblenv/blob/master/iblenv.yaml#L2) be updated to have conda-forge as higher priority:
```
-channels:
   -conda-forge
   -defaults
```

 With the current iblenv list, `pyarrow==0.15.1` is downloaded which breaks ibllib. 
Maybe in the future, pyarrow version on pip will be fixed!

@oliche my current env.yaml file is 
[iblenv_temp.txt](https://github.com/int-brain-lab/ibllib/files/5240646/iblenv_temp.txt)

**Comment by oliche** [comment]
So in this case uninstall the pip version and install via conda fixed it:
```
pip unistall pyarrow
conda install pyarrow
```

Related issue for opencv: depending on the OS and environment, sometimes only the pip version works, sometimes only the conda version works.

Closing it.
