### ISSUE TITLE
.ch file about raw compression not registered 

### ISSUE THREAD

**Issue by Saksham20** [int-brain-lab/ibllib#212]
**Describe the bug**
- **ephysData.raw.nidq** : cannot find any **.ch** files for these datasets (example: `_spikeglx_ephysData_g0_t0.nidq.ch`) for many tried eids. Even though the .cbin, .meta files exist, but due to lack of .ch, it cannot be decompressed. 
- **audiospectrogram.times_mic**: this is an array `(no_time_windows,) ` with each element being a list of single float value instead of simply a float time value. Is this how its designed to be? So for example to access the first time element: `times_mic[0][0]`

**To reproduce ephysData.raw.nidq error**:
```python
from oneibl.one import ONE
import numpy as np
from ibllib.io import spikeglx
one=ONE()
nidq = one.search(dataset_types=['ephysData.raw.nidq'])
nidq_data=[]
nidq_data_ch=[]
nidq_data_meta=[]
for i in np.arange(0,200,50):
   nidq_data.append(one.load(nidq[i], dataset_types=['ephysData.raw.nidq']))
   nidq_data_ch.append(one.load(nidq[i], dataset_types=['ephysData.raw.ch'])) 
   nidq_data_meta.append(one.load(nidq[i], dataset_types=['ephysData.raw.meta']))

nidq_data_decomp=[]
for i in nidq_data:
    nidq_data_decomp.append(spikeglx.Reader(i[0]))
```
As expected, Loading `nidq_data_decomp` using spikeglx throws the error for not found .ch files 

**To reproduce audiospectrogram.times error**:
```python
one=ONE()
eid_raw_behavior='383f300e-ff4e-479a-8967-a33ea51b436e'
audio_spec_times = one.load(eid_raw_behavior,dataset_types=['_iblmic_audioSpectrogram.times_mic'])
```
output
```python
audio_spec_times[0][0][0]
Out[11]: 0.6553575
```
Expected: 
```python
audio_spec_times[0][0]
Out[11]: 0.6553575
```

**Comment by mayofaulkner** [comment]
Thanks for pointing these missing datasets out. We are now uploading and patching the data and they should be on the server with in the next couple of days!

**Comment by oliche** [comment]
mainenlab data has been fixed.
Now registering other labs, should be finished over the week-end.
