### ISSUE TITLE
TODO for doc : definition of data dimension

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/ibllib#22]
TODO for doc: need to define data dimension (e.g. ‘clusters.templateWaveforms’, ‘clusters.probes’, ‘clusters.depths’).
e.g.  ‘clusters.templateWaveforms’: NxMxW where N = number of spikes, M = time, W = shank etc.

Happy to do the doc, but I could not find this info anywhere.

**Comment by k1o0** [comment]
This is now in the [dataset types document](https://docs.google.com/document/d/1OqIqqakPakHXRAwceYLwFY9gOrm8_P62XIfCTnHwstg/edit#heading=h.n9ud7857dkqw).
