### ISSUE TITLE
downloaded datasets as lists of probes not consistently ordered

### ISSUE THREAD

**Issue by Saksham20** [int-brain-lab/ibllib#226]
I downloaded two datasets: clusters.metrics and clusters.waveforms. They are a list of len no of probes but they are not ordered consistently:

**To Reproduce**
```python
eid = 'da188f2c-553c-4e04-879b-c9ea2d1b9a93'
clusters_waveforms = one.load(eid,dataset_types=['clusters.waveforms'])
clusters_metrics = one.load(eid,dataset_types=['clusters.metrics'])
#clusters_waveforms[0].shape[0]==clusters_metrics[1].shape[0]
#clusters_waveforms[1].shape[0]==clusters_metrics[0].shape[0]
```
Ideally, shouldn't the lengths of the each of the dataset in the list be the same corresponding to the same probe? Does the ONE api maintain the order?

**Comment by oliche** [comment]
There is an ambiguity here as there are several datasets types for the same eids (ie. for each probe).
The probes are arbitrary, there can be many, only one, some may have spike sorting some may not, so we should expect the sizes to be inconsistent.

We are addressing this in ONE2 by preventing the users to load blindly dataset types, but in the meantime, here is a recommended way to load data for each probe:

```
from oneibl.one import ONE
import alf.io
one=ONE()

eid = 'da188f2c-553c-4e04-879b-c9ea2d1b9a93'
cfiles = one.load(eid,dataset_types=['clusters.waveforms', 'clusters.metrics'], download_only=True)
probe_paths = set([p.parent for p in cfiles])
clusters = {}
for probe_path in probe_paths:
    clusters[probe_path.parts[-1]] = alf.io.load_object(probe_path, 'clusters')
```

Note that here we download whatever is available and then bulk load every attribute of the cluster object.
