### ISSUE TITLE
Help search function for information on data dimension

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/ibllib#25]
Create help search function that allows to search on dataset_type and displays information.
 
Information: as given in dataset_details (see example below), BUT ALSO meaning of dataset dimension. 

```
[dataset_type , dataset_details] = one.list(eid)

ans =

  2×1 cell array
    'clusters.templateWaveforms'
    'eye.area'
```

```
% Help function, something like: 
one.help.dataset('clusters.templateWaveforms')
```
displays
```
 Dataset_type: clusters.templateWaveforms
 Dimension: NxMxT , where N = ... , M = ..., T = ... 
 Data format: ... % info in dataset_details
 (etc other useful info)
```

**Comment by oliche** [comment]
Ok so proposition is to do a query on the description field of Alyx.

**Comment by rossant** [comment]
@GaelleChapuis  is this still needed?

**Comment by GaelleChapuis** [comment]
Information can be found via this public sheet: 
https://docs.google.com/spreadsheets/d/1ieLXRPLLSgUKcLvFkrqizfZl5HjdfE6bQ2KLBCRmjQo/edit?usp=drivesdk
