### ISSUE TITLE
Empty stimOn_times

### ISSUE THREAD

**Issue by alejandropan** [int-brain-lab/ibllib#33]
When using one.load I get empty stimOn_times for all the trials in certain sessions (e.g ibl_witten_02, 2018-01-07)

**Comment by oliche** [comment]
Yes so the file is empty so the one.load behaviour is normal. We need to check the extractors though as it may be an extraction issue.

**Comment by oliche** [comment]
@nbonacchi this is a rig issue, the whole session ran without the BNC of the photodiode connected. Created issue there: https://github.com/int-brain-lab/iblrig/issues/66
