### ISSUE TITLE
call left/right probes 00/01 on flatiron

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/ibllib#355]
Some sessions have folders in alyx of the two probes with names "probe_left" and "probe_right" (e.g. this one https://ibl.flatironinstitute.org/cortexlab/Subjects/KS004/2019-09-25/001/alf/) while most others have "probe00", "probe01". Maybe someone wants to run a loop to rename all to probe00 and probe01 for consistency?

**Comment by mschart** [comment]
This was an issue for me while I did the following analysis. For all sessions that had motion energy, I computed a p-value that indicates how whisking is block-modulated. For each of these sessions, I next pooled neurons from all probes and computed a p-value to indicate how neural activity is block-modulated, such that I could see if those with block-modulated neural activity have block-modulated whisking. 

To do so, I had a list of eids and for each eid, I loaded (and combined) spikes from two probes in a loop, assuming there are two probes and they are called probe00/01, like so (see full script [here](https://github.com/int-brain-lab/paper-brain-wide-map/blob/main/manifold_analysis/state_space_bulk.py#L77)):


```
def bin_neural(eid, double=True, probe=None, reg=None):
    '''
    bin neural activity; combine probes or pick single region
    ''' 
    one = ONE()    
    dataset_types = ['spikes.times','spikes.clusters','clusters.channels']
    
    D = one.load(eid, dataset_types = dataset_types, dclass_output=True)
    local_path = one.path_from_eid(eid)  
    alf_path = local_path / 'alf'  
    
    if probe is not None:
        double = False
    
    
    if double:
        print('combining data from both probes')
        sks = []
        for probe in ['probe00','probe01']:    
            probe_path = alf_path / probe    
            spikes = alf.io.load_object(probe_path, 'spikes')
            sks.append(spikes)
         
        # add max cluster of p0 to p1, then concat, sort 
        max_cl0 = max(sks[0]['clusters'])
        sks[1]['clusters'] = sks[1]['clusters'] + max_cl0
         
        times_both = np.concatenate([sks[0]['times'],sks[1]['times']])
        clusters_both = np.concatenate([sks[0]['clusters'],sks[1]['clusters']])
        
        t_sorted = np.sort(times_both)
        c_ordered = clusters_both[np.argsort(times_both)] 
        
        print('binning data')
        R, times, _ = bincount2D(t_sorted, c_ordered, T_BIN)  

        D = R.T            
        
    else:    
        print('single probe') 
        local_path = one.path_from_eid(eid)  
        alf_path = local_path / 'alf'     
        probe_path = alf_path / probe
        
        spikes = alf.io.load_object(probe_path, 'spikes')
          
     
        # bin spikes
        R, times, Clusters = bincount2D(
            spikes['times'], spikes['clusters'], T_BIN)
       
        D = R.T       
        
        if reg is not None:
            
            # Get for each cluster the location x,y,z
            clusters = alf.io.load_object(probe_path, 'clusters')
            cluster_chans = clusters['channels'][Clusters]      
            els = load_channel_locations(eid, one=one)   
            acronyms = els[probe]['acronym'][cluster_chans]       
            m_ask = acronyms == reg
            D = D[:,m_ask]

    return D, times 
```

**Comment by k1o0** [comment]
The probe labels are not standardized and will probably change in the future.  The best thing to do would be to load the data in a way that is agnostic to the probe label.  One thing you could do is use `brainbox.io.one.load_spike_sorting` or `brainbox.io.one.load_spike_sorting_with_channel` which will by default return a dict with the probe labels as keys. 

Or you could get a list of probe labels by inspecting the 'probes' object:
```
probes = one.load_object(eid, 'probes', collection='alf')
labels = [pr['label'] for pr in probes['description']]
```
