### ISSUE TITLE
one.load_object TypeError: can only concatenate str

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/ibllib#399]
In [26]: eid = '5386aba9-9b97-4557-abcd-abc2da66b863'

In [27]: one.load_object(eid, 'trials')
TypeError: can only concatenate str (not "NoneType") to str

Maybe that's temporary ...

**Comment by k1o0** [comment]
I can't reproduce this error.  Do you have the full stack trace?  Also in future make sure you open up your issues in iblenv because we rarely look here...
