### ISSUE TITLE
Typo in brainbox.behavior.psychofit

### ISSUE THREAD

**Issue by berkgercek** [int-brain-lab/ibllib#415]
I honestly thought I was going crazy for weeks because whenever I tried to import psychofit in ipython, I would get an error from:

` from brainbox.behavior.psychofit import erf_psycho_2gammas `

saying the module `brainbox.behavior.psychofit` doesn't exist.

It turns out it doesn't! It's `pyschofit`, which is either a subtle py- renaming or a typo.

I think this is a module used fairly heavily in determining whether mice are ready for ephys based on behavioral criterion, so I'm hesitant to suggest we change it immediately for fear of forcing a multi-repo refactoring, but we should probably make the name `psychofit` as one would expect before we go live with the data, at least.

Or just pretend it was intentional and change all the docstrings in the module... :-)

**Comment by anne-urai** [comment]
Hasn't this moved to its own package? https://pypi.org/project/Psychofit/

**Comment by k1o0** [comment]
It has indeed. This is a stale issue though. I don't know whether pyschofit was supposed to be a pun but it was confusing and is now back to the correct name!
