### ISSUE TITLE
wheelMoves object

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#46]
@anne-urai pointed out that the wheel moves ALF object is not extracted on the Python rigs.  We want to begin doing wheel movement analysis with these traces.  What's the status of this? 

If you think this will be difficult to implement it could in theory not be an ALF file but instead be calculated in DataJoint.

**Comment by oliche** [comment]
I see it as part of the extraction process, so to be run on the rigs before Alyx upload.

**Comment by GaelleChapuis** [comment]
Is this now done ?
