### ISSUE TITLE
all choices in trainingChoiceWorld are logged as 0

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/ibllib#49]
all ONE sessions generated with the new `trainingChoiceWorld` have `choice`== 0, which should be reserved for no-go (i.e.  missed) trials

**Comment by anne-urai** [comment]
great, thanks for the quick fix - can you give instructions for the re-extraction?

**Comment by oliche** [comment]
It's all done on the server end, no need to do anything on your end. I've warned Datajoint as well.

**Comment by anne-urai** [comment]
this still seems to be a problem after updating to 3.7.1

**Comment by oliche** [comment]
Keep it open until data is actually re-extracted. Waiting for confirmation that all rigs are updated and problem is fixed before doing re-extraction.
