### ISSUE TITLE
Historic weighings in Subjects rest endpoint

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ibllib#50]
Answer to Slack message.

So the subjects endpoint has 2 behaviours:
list, which returns multiple subjects depending on the filter `sub = one.alyx.rest('subjects', 'read', 'IBL_11')`
details, which returns subjects matching nickname:
`sub = one.alyx.rest('subjects', 'read', 'IBL_11')`

The details endpoint returns full weighings and water_administrations history for a subject.

```
from oneibl.one import ONE
one = ONE()

sub = one.alyx.rest('subjects', 'read', 'IBL_11')
for w in sub['weighings']:
    print(w['weight'], w['date_time'][:10])

for wa in sub['water_administrations']:
    print(wa['water_administered'], wa['date_time'][:10])
```

**Comment by anne-urai** [comment]
thanks - is this difference in behavior between `one.alyx.rest('subjects', 'read', mousename)` and `restr = one.alyx.get('/subjects/%s' %mousename)` explained somewhere in the documentation?

**Comment by oliche** [comment]
It's equivalent. From our perspective, `restr = one.alyx.get('/subjects/%s' %mousename)` would have been private is there had been private methods in Python, and as such should not be in documentation.
