### ISSUE TITLE
Ambient sensor data access

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ibllib#51]
They are on the Flatiron:
```
sessions, details = one.search(dataset_types='_iblrig_ambientSensorData.raw', lab='churchlandlab')
asd = one.load(sessions[0], dataset_types='_iblrig_ambientSensorData.raw')
```
There is one temperature/pressure value per trial.

**Comment by anne-urai** [comment]
The commands above return `asd = None` even though the jsonable loads onto disk fine

**Comment by oliche** [comment]
Hmm this is not reproducible here. Possible explanations:

- this happens to most recent datasets: the datasets are registered, but do not exist yet on flatIron and `none` is the expected behaviour
- it happens to all datasets: fb757883278f770b9145fbaa4b3facc20a3d7974 was implemented 19 days ago on master. You should be up to date but still worth checking

Otherwise, please send a specific session that has this behaviour, and I"ll see if I can reproduce. Which OS ?

**Comment by nbonacchi** [comment]
the code above is missing a `..., details=True)`

**Comment by anne-urai** [comment]
Updating to the latest develop branch fixed the `None` problem.
Could importing `one.ibllib` throw a warning when the user is on an old version?

Also, the output returned is a cumbersome list of dicts of lists (I think?):
```
   'RelativeHumidity': [32.5419921875]},
  {'Temperature_C': [26.780000686645508],
   'AirPressure_mb': [1011.332763671875],
   'RelativeHumidity': [32.552734375]},
  {'Temperature_C': [26.770000457763672],
   'AirPressure_mb': [1011.30322265625],
   'RelativeHumidity': [32.5634765625]},
  {'Temperature_C': [26.790000915527344],
   'AirPressure_mb': [1011.3099365234375],
   'RelativeHumidity': [32.564453125]},
  {'Temperature_C': [26.780000686645508],
   'AirPressure_mb': [1011.3465576171875],
   'RelativeHumidity': [32.564453125]}]]
```
So that `ambient = pd.DataFrame(asd[0])` returns
```
           AirPressure_mb RelativeHumidity         Temperature_C
0    [1010.5851440429688]    [33.04296875]  [26.219999313354492]
1    [1010.7210083007812]  [33.3408203125]  [25.989999771118164]
2    [1010.6853637695312]  [33.3408203125]  [25.979999542236328]
```

Could the dict values be numeric, rather than wrapped in a list? And what datasetType should I grab to get the timing for each of these (`stimulus_onTime`?)
