### ISSUE TITLE
allow loading of multiple eid in one call

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/ibllib#52]
when a `one.search` returns a list of `eids`, it would be great to pass this to `one.load` (returning for example a list of data, or even better the appended data) rather than having to load each session in a loop

**Comment by oliche** [comment]
Yes this was clearly overdue. 476984efcc150c3895fa5e236ebcdfb61656b3b0
`one.load(eids, dclass_output=True)`

I still have to add something to limit the data loading, here one can blow up the RAM easily by loading data from the beginning.
