### ISSUE TITLE
missed trials: set response time to NaN, and feedbackType to -1

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/ibllib#54]
'Missed' (i.e. no response within 1minute) trials are currently coded in Alf in a way that's a bit confusing. When `choice == 0`, it would be helpful if `response_times == NaN`, and `feedbackType == -1` (since I believe the punishment tone played is the same after a miss?

**Comment by nbonacchi** [comment]
regarding feedbackType I agree, the feedback was 0 because I was under the impression that we might want to give a different feedback to no_go trials... simple fix.

Regarding response_times, I think you are interpreting this datasetType in the colloquial way of how-long-it-took-the-animal-to-respond.

**Comment by anne-urai** [comment]
I understand that _times is special, and I'm using responseTimes and stimulusTimes to compute the animal's reaction time per trial. 

But when the trial was 'missed', does it make sense to log a responseTime of 60 seconds after the stimulus - even though the animal just sat there? I think it makes more sense to put a NaN there, since on that trial this event didn't occur.

**Comment by nbonacchi** [comment]
Yes it does:
response_times goes with choices (that was actually supposed to be called responses) where each response -1, 0 or 1 has a time at which it was recorded. Meaning "I"
recorded the response 0 at time 125.456 seconds from session start...

**Comment by anne-urai** [comment]
i think this is counterintuitive (the mouse never made a response on trials where choice is 0, so there shouldn't be a time logged) but i will make sure that the wrappers set these to NaN to avoid confusion

**Comment by nbonacchi** [comment]
the mouse never made a response on trials where choice is 0...
That's not totally correct. In no_go, we have no way of knowing if the mouse was going to make a response or not, we record the time at which we make an arbitrary decision to restart a trial. The response is not of the mouse. Plus, if we decide to change the 60 seconds to e.g. 30 or change this time on a trial by trial basis we would be able to recover this just by looking at the response_times.

Again, the best way of thinking about it is not the time at which the mouse responded, but rather, the time at which an event was detected. This can be a position in the rotary encoder in which case we can call it a mouse response or a time limit where none of these positions were reached and we can call it a task response or a world response.
