### ISSUE TITLE
oneibl_rig report command

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/ibllib#55]
right now, the user has to take a few daily steps to make sure data are transferred - and things can go wrong for a few of them, which has led to data not appearing on flatiron (and therefore datajoint) for a while.

it would be great to have a system where these discrepancies are flagged to the user (and the data coordinator?) so that we don't have a data backlog that's too long. since we don't have psychometric functions and many other crucial things plotted during training in pybpod, only seeing the data a few days later can be a problem for diagnosing problems with the animals in a timely manner.

**Comment by oliche** [comment]
Something like:
`python one_iblrig.py report /path/to/my/sessions/ --dry=True --count=5`
