### ISSUE TITLE
one.search to return eid's for any() of the dataset types instead of all()

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/ibllib#56]
So for example:
```pyhon
one.search(lab='mainenlab', dataset_types=['_ibl_trials.goCue_times', '_ibl_trials.goCueTrigger_times.npy',], any=False)
```
returns all eIDs from the mainenlab that have _ibl_trials.goCue_times **AND** _ibl_trials.goCueTrigger_times, recapitulating the current behavior so we can have `any=False` as default.

but 

```pyhon
one.search(lab='mainenlab', dataset_types=['_ibl_trials.goCue_times', '_ibl_trials.goCueTrigger_times.npy',], any=True)
```
would return all eIDs from the mainenlab that had either _ibl_trials.goCue_times **OR** _ibl_trials.goCueTrigger_times.

**Comment by oliche** [comment]
I think for this the best is to do 2 queries
