### ISSUE TITLE
URL problem while retrieving file from flatiron

### ISSUE THREAD

**Issue by joacorapela** [int-brain-lab/ibllib#566]
**Describe the bug**
While running the script below, ONE displays the following error:
```
HTTP Error 404: Not Found https://ibl.flatironinstitute.org/public/hoferlab/Subjects/SWC_043/2020-09-21/1.0/raw_ephys_data/probe00/_spikeglx_ephysDatag0_t0.imec0.lf.99c957a8-f664-463b-afae-a1ba570a85b2.cbin
```
Looking at https://ibl.flatironinstitute.org/public/hoferlab/Subjects/SWC_043/2020-09-21/ I see that the directory 1.0 does not exist, but the directory 001 does.

**To Reproduce**
1. run the script below

```python
import sys
import argparse
import numpy as np
import scipy.signal

import one.api
import brainbox.io.spikeglx


def main(argv):
    pid = 'da8dfec1-d265-44e8-84ce-6ae9c109b8bd'
    time0 = 100 # timepoint in recording to stream
    time_win = 10 # number of seconds to stream
    band = 'lf' # either 'ap' or 'lf'

    aOne = one.api.ONE(base_url='https://openalyx.internationalbrainlab.org',
                       password='international', silent=True)
    sr = brainbox.io.spikeglx.Streamer(pid=pid, one=aOne, remove_cached=False,
                                       typ=band)
    s0 = time0 * sr.fs
    tsel = slice(int(s0), int(s0) + int(time_win * sr.fs))

    # Important: remove sync channel from raw data, and transpose
    lfp = sr[tsel, :-sr.nsync].T
    nChans, nSamps = lfp.shape
    print(f"Data has {nChans} channels and {nSamps} samples")

    breakpoint()


if __name__ == "__main__":
   main(sys.argv)

```
**Desktop (please complete the following information):**
 - OS: linux (Debian)
 - Browser chrome
 - Version Version 109.0.5414.119 (Official Build) (64-bit)
one-api                   1.17.0                   pypi_0    pypi

**Comment by k1o0** [comment]
Hello joacorapela,

That's for letting us know.  We've fixed our database cache tables so your code should now work.  The next time you run your code it should automatically download the newer cache tables, however if you still have issues you can run `aOne.load_cache(clobber=True)` to force a re-download.

I'm closing this issue for now but feel free to re-open it if you still have problems.

**Comment by joacorapela** [comment]
Thanks a lot for your help k1o0. After forcing re-download the code is
running 🙂

J.
