### ISSUE TITLE
Adding a field on Alyx to query for subject training status

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ibllib#595]
One ONE is released, create page on Loading the Data in iblenv documentation. (Miles)

-----
We need to query per training status, e.g. we want to know:

How many mice have reached a given training status, and how many sessions are there before this status is reached?

Proposal:

Have a field `session__extended_qc__training_status`
which would be either **null** when the mouse has not done any transition switch, or have a value, e.g. **trained** , upon the mouse reaching a given criteria.

In essence this field `session__extended_qc__training_status` would only exist when the mouse reaches a given criteria, so it should appear ~4 times per mouse (values can be: trained, ready4ephysrig , ready4delay, ready4recording and untrainable, if not missing anything).

Use the trials table to compute the criteria ; add the output to the table also.

    Save as multi-index eid/trial#
    Hash the dataset ids + dataset md5 as run id
    Is it possible to recompute the training status only from the trials information ?

**Comment by oliche** [comment]
From @k1o0 
``` 
def query_criterion(subject, status, from_status=None, one=None):
    """
​
    Parameters
    ----------
    subject : str
        The subject name.
    status : str
        The training status to query for.
    from_status : str, optional
        Count number of sessions and days from reaching `from_status` to `status`.
    one : one.api.OneAlyx, optional
        An instance of ONE.
​
    Returns
    -------
    str
        The eID of the first session where this training status was reached.
    int
        The number of sessions it took to reach `status` (optionally from reaching `from_status`).
    int
        The number of days it tool to reach `status` (optionally from reaching `from_status`).
    """
    one = one or ONE()
    subject_json = one.alyx.rest('subjects', 'read', id=subject)['json']
    if not (criteria := subject_json.get('criteria')) or status not in criteria:
        return None, None, None
    to_date = criteria[status]
    from_date = criteria.get(from_status)
    eids, det = one.search(subject=subject, date_range=[from_date, to_date], details=True)
    date_range = list(map(datetime.date.fromisoformat, (det[0], det[-1])))
    return eids[-1], len(eids), (date_range[1] - date_range[0]).days
```

**Comment by oliche** [comment]
- compute from trial table (although it needs input from the task parameters)
- update the extraction task to update JSON field
- (create the queries if non-obvious)

**Comment by GaelleChapuis** [comment]
Documentation ; query
