### ISSUE TITLE
Upload released versions of ibllib to pypi

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/ibllib#64]
`pip install ibllib`
(Added cyrille as I'm sure he has more experience of doing this)

This all started because of pagination in Alyx. The REST endpoint will answer differently once it's implemeted and will break the alyx client of the pybpod module.To make this and future changes more maintainable alyx itself could have a python alyxclient somewhere. Alas, sharing small modules of a bigger project is not very easy (maybe gists?).

Alternatively, and we coul do this immediately, to improve maintainability the pybpod module could use the alyxclient of ibllib. To do this we should publish ibllib in PyPI as cloning and installing a repo is not very streamlined. addinig ibllib to the dependencies of any other repo would however be a no brainer.

I guess the main obstacle is the ciso8601 wheel that does not build out of the box in windows...

**Comment by rossant** [comment]
I think you can also do `pip install git+https://github.com/toto/titi.git` to install directly from GitHub, without having to upload the package to pypi.

As you say, things get an order of magnitude more complicated when stuff has to be compiled. Is there no alternative to using a C extension?

**Comment by nbonacchi** [comment]
@oliche is probably the best person to answer this...

I also would go with something pip installable in both windows and linux. If one uses `conda install` it works. Anaconda builds the wheel and redistributes it for ciso8601==2.1.1 

I also use this in my requirements file:
`-e git+https://github.com/int-brain-lab/ibllib.git#egg=ibllib&subdirectory=python`
I use `-e`to install in place for updates of just ibllib, it gives me the illusion of control, somehow I prefer doing a `git reset --hard && git pull` rather than a `pip install --force-reinstall git+https://github.com/int-brain-lab/ibllib.git#egg=ibllib&subdirectory=python`

Anyway I can try to talk to the PyBpod guys to see if they'll use the pip/git install procedure in the mean time.
