### ISSUE TITLE
Fix missing spike sorting runs for Felicia and others

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/ibllib#654]
Data seems not extracted or not registered ; unclear

Unable to load the spike sorting data from the alignment GUI

Thread here https://int-brain-lab.slack.com/archives/CEM70EXTN/p1696378520197759

**Comment by oliche** [comment]
The main symptom is the alignment GUI that can't find the spike sorting.

There are 2 issues at hand here.

1) The spike sorting ran fine, but for those recordings the probe name in Alyx does not match the probe name on disk, the probe insertions have to be updated with the correct name and the spike sorting loader will find those.

This affects the following recordings 
```
004d8fd5-41e7-4f1b-a45b-0d4ad76fe446 MFD_05 2023-08-17 ['d65ab768-bd77-4719-acb9-677abca4e9d8'] ['probe01'] on disk ['probe00']
35eeb752-8f4f-4040-9714-ba0f5b7ccdfe MFD_06 2023-08-22 ['069c2674-80b0-44b4-a3d9-28337512967f'] ['probe01'] on disk ['probe00']
3f71aa98-08c6-4e79-b4c8-00eae4f03eff MFD_06 2023-08-25 ['17fa2600-6349-4b6f-a7e4-d8ea5558fa12'] ['probe01'] on disk ['probe00']
c46b8def-620d-4d70-9397-be5694255f73 MFD_07 2023-08-29 ['06b677d6-b074-4444-bd4a-3235a310e6e0'] ['probe01'] on disk ['probe00']
c8372676-0e5b-47dd-824b-08f841e5b572 MFD_07 2023-08-30 ['6b3580f8-10b0-4e38-97c5-800ce9196ea0'] ['probe01'] on disk ['probe00']
```

2) The spike sorting is failing with a CUDA illegal memory address
MFD_08 2023-09-06 ['c78432d0-42b0-4837-ab64-bc68918f38a9'] ['probe00'] on disk ['probe00']

https://alyx.internationalbrainlab.org/admin/jobs/task/a82fa269-a074-4e1e-8cef-131678e64b7a/change/

**Comment by oliche** [comment]
We keep track of  spike sorting re-runs using 1.5.0 here. This version fixes some of the out of memory errors on GPU. https://docs.google.com/spreadsheets/d/19skWz5ubkJ1wAeDeKU_nsiqxMKk0B4zdujcIzbAiUU8/edit#gid=0

**Comment by chris-langfield** [comment]
All of these:
```
004d8fd5-41e7-4f1b-a45b-0d4ad76fe446 MFD_05 2023-08-17 ['d65ab768-bd77-4719-acb9-677abca4e9d8'] ['probe01'] on disk ['probe00']
35eeb752-8f4f-4040-9714-ba0f5b7ccdfe MFD_06 2023-08-22 ['069c2674-80b0-44b4-a3d9-28337512967f'] ['probe01'] on disk ['probe00']
3f71aa98-08c6-4e79-b4c8-00eae4f03eff MFD_06 2023-08-25 ['17fa2600-6349-4b6f-a7e4-d8ea5558fa12'] ['probe01'] on disk ['probe00']
c46b8def-620d-4d70-9397-be5694255f73 MFD_07 2023-08-29 ['06b677d6-b074-4444-bd4a-3235a310e6e0'] ['probe01'] on disk ['probe00']
c8372676-0e5b-47dd-824b-08f841e5b572 MFD_07 2023-08-30 ['6b3580f8-10b0-4e38-97c5-800ce9196ea0'] ['probe01'] on disk ['probe00']
```
except the last one were fixed (the last one had a CUDA error and the spike sorting never went through)

**Comment by chris-langfield** [comment]
Consolidated cuda errors issue: https://github.com/int-brain-lab/pykilosort/issues/25
