### ISSUE TITLE
Recent mesoscope extractions failing

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#680]
@samupicard is currently making a list of sessions with more varied data (low SNR, different depths, etc) to pass along to Amol for PMD testing. The issue is that most of these have not been fully extracted yet, so we don't have a suite2p binary for them. We need to determine why the following sessions have not had suite2p run:

- [x] SP044\2023-06-27\001: 12 FOVs (6 scanfields at 2 depths each)
- [x] SP046\2023-11-27\001: 6 FOVs (6 scanfields at 1 single depth)

**Comment by mayofaulkner** [comment]
Check in with Samuel and ask if sessions are still priority

**Comment by samupicard** [comment]
These particular sessions are not a priority anymore as I ran suite2p myself on these sample datasets. But it would be great to investigate why the suite2p task fails to run on so many sessions.
