### ISSUE TITLE
Restore ITI QC check for v8 sessions

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#686]
We removed the ITI delay QC check because of a bug in v7.  This bug should now be fixed for recent versions of iblrig, so we should restore this QC check for those sessions.  @GaelleChapuis I would argue that the QC should be warning rather than not set, so that it is clear to future users that older sessions have this issue.

**Comment by GaelleChapuis** [comment]
Yes, setting it to WARNING for previous sessions make sense to me.
