### ISSUE TITLE
Concurrent ibllib workflow builds fail

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#688]
Concurrent tests failing in ibllib github workflow. Seems to be related to the test database. Example: https://github.com/int-brain-lab/ibllib/actions/runs/7196254600/job/19600699079

This only happens on PRs from develop to master as there are 4 concurrent builds running (2 are redundant, triggered by both a push to develop and a PR to master).

One solution is to modify the workflow to eliminate this redundancy. Another is to figure out why these tests fail.

**Comment by mayofaulkner** [comment]
Concurrency settings - force to only run 2 builds at same time

**Comment by mayofaulkner** [comment]
Changed the number of concurrent workflows to 2 in PR #698 . Let's see if this helps in the long run

**Comment by k1o0** [comment]
Sadly concurrent tests still fail :( It's difficult to determine why exactly.

**Comment by GaelleChapuis** [comment]
Revert changes to worksflow

**Comment by k1o0** [comment]
ce5406c8773b34172889acae6edc55663f105370 most likely fixes these issues by vastly reducing the likelihood of session conflicts.
