### ISSUE TITLE
Document how to run task QC

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#693]
- [x] Move `get_trials_tasks` to ibllib.pipes https://github.com/int-brain-lab/ibllib/pull/690
- [ ] Document how to run the QC for a session in module docstring
- [ ] Ensure Google docs are deleted or updated

May be worth having a notebook on QC?

**Comment by GaelleChapuis** [comment]
made a new file `iblrig/docs/source/task_qc.rst` into the `docs` branch, and also amended the index so it’s contained in the table of content, but I do not see anything appearing on the main website

**Comment by GaelleChapuis** [comment]
Docs deployed https://int-brain-lab.github.io/iblrig/task_qc.html
