### ISSUE TITLE
New version is incompatible with Python 3.8

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ibllib#701]
This syntax is incompatible with version 3.8 and has caused issues with Nate's server.
I've just upgraded Python on his server but we need to make a decision if we fix it or if it is time to drop support for 3.8 (and possibly 3.9)

A discussion about a Python release schedule compatibility would be beneficial in the dev team

Offending line is here:
https://github.com/int-brain-lab/ibllib/blob/0e78b96187966f6a96d89af0e7a49bee16d222b0/ibllib/io/extractors/ephys_fpga.py#L1486

**Comment by k1o0** [comment]
Fixed in version 2.28
