### ISSUE TITLE
Updates to the way revisions and default datasets are created

### ISSUE THREAD

**Issue by juhuntenburg** [int-brain-lab/ibllib#728]
Problem 1:
When tasks are rerun and the output data are protected, a revision of the output datasets is created automatically. This leads to a situation where users can rerun a task (for whatever reason) and we have new default datasets. It is hard to understand if there was a reason for the revision or if it was a "mistake".

Problem 2:
When rerunning a task on cortexlab server, data might be overwritten even if it is protected as datasets are only protected on IBL alyx and cortexlab alyx is "blind" to this and doesn't know to create a revision instead of overwriting.

Solution:  
Default behavior when trying to overwrite a protected dataset should be an error with an option to force creation of the revision dataset. This way we could have more reason to believe that revisions were created on purpose rather than by accident. For the cortexlab server we need to make sure that we check if the data is protected **on the IBL alyx database** by pinging the endpoint returning all protected data on IBL alyx database from cortexlab server. On the cortexlab server we just error out in this case and don't give the option to create a revision because it creates all sorts of problems for importing data. Instead, if we really want to make a revision on a protected dataset from cortexlab, we can just rerun these tasks on a different server or SDSC and register it directly with IBL alyx.

**Comment by k1o0** [comment]
FYI The automatic creation of a new revision occurs within the except block of `RegistrationClient.register_files`: https://github.com/int-brain-lab/ONE/blob/22f297270e0bb207b820b0e2328fd37e0cfd0910/one/registration.py#L507
