### ISSUE TITLE
Make patcher work with revisions

### ISSUE THREAD

**Issue by juhuntenburg** [int-brain-lab/ibllib#737]
Error occurs when using patcher to register data (in this case SDSC patcher, but I think this is a general issue?) in the case that the output data exists and is protected and therefore a revision is created.

This assertion fails: https://github.com/int-brain-lab/ibllib/blob/master/ibllib/oneibl/patcher.py#L116

The issue (I believe) lies here: https://github.com/int-brain-lab/ibllib/blob/master/ibllib/oneibl/patcher.py#L188
The paths in file_list are no longer the actual paths if the data has been moved into a revision folder. I think we could use d['filenames'] instead of p (from file_list) because I think it should contain the actual path of the files in the revision folder, but haven't actually tested this

**Comment by mayofaulkner** [comment]
Patcher modified in ibllib 2.32.0
