### ISSUE TITLE
Raw Ephys QC

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ibllib#76]
1) Instead of 2 2D outputs: RMS (channel, window time),  and PSD(frequency, channel)
output a single 3D output containing spectrogram ( channel, window time, frequency).
Make sure the median/mean accross frequency dimension matches the RMS (Parseval) so that units are relevants.

2) Extract specific FFT samples at 50 and 60 Hz and harmonics to quantify line noise.

**Comment by GaelleChapuis** [comment]
Once 1. is done, do 3. average over specific LFP bands (apha, beta etc) so as to show for each band, the power in each channel over time as heatmap.
