### ISSUE TITLE
WARNING  [registration.py:180] No matching dataset type for: \..\_iblrig_micData.raw.wav

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/ibllib#79]
I have this warning during registration training sessions and I am wondering if that is something related to data acquisition from the microphone? Should I ignore this? 
`2019-06-11 18:39:30.814 WARNING  [registration.py:180] No matching dataset type for: C:\globus_server\Subjects\KS009\2019-06-11\001\raw_behavior_data\_iblrig_micData.raw.wav`

**Comment by oliche** [comment]
So this is done on purpose, we do not want to register and upload the microphone data for training sessions as it is too big to save in perspective of its usefulness.
We'll certainly have it for ephys sessions.
