### ISSUE TITLE
Quality control METRICS on sessions / datasetTypes for "Choice World" tasks

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/ibllib#83]
The Alyx repo is discussing adding flags to dataset and session objects. 
https://github.com/cortex-lab/alyx/issues/562
Of course this means that we need to decide what are those metrics and what would make sense for our particular case.
This issue should be a list of thos metrics, the more detailed possible:

**Comment by oliche** [comment]
https://docs.google.com/a/internationalbrainlab.org/document/d/1X-ypFEIxqwX6lU9pig4V_zrcR5lITpd8UJQWzW9I9zI/edit?disco=AAAADPsrTr8
