### ISSUE TITLE
Data release white paper updates

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/ibllib#835]
The white paper on data release needs updating for the resubmission of the BW paper:
https://www.overleaf.com/project/634d7d7f9cdfe00b07009709
https://figshare.com/articles/preprint/Data_release_-_Brainwide_map_-_Q4_2022/21400815?file=38761482

- [x] L68-71: N mice / units / insertions / sessions
- [x] L 74: coverage % with 1 probe
- [x] L78: verify criteria for region inclusion, N region included
- [x] Figure 2: panel a-b redo
- [x] L98: QC sheet: update with latest insertions / sessions
- [x] L101: Do we still use iblenv issues ? -- keep for now
- [x] L113-115: N mice, age, weight
- [x] L202: coverage % with 1 probe and 2 probes
- [x] L223: check amplitude criteria
- [x] L226: N units and good units
- [x] L256: raw video QC numbers
- [x] L272: pose estimation QC numbers
- [x] L285: pupil QC numbers
- [x] L293: raw ephys and spike sorting QC numbers -- unchanged
- [x] L374: pykilosort reference into iblsort
- [x] L267/270: remove "github repository" links, replace with docs links
- [x] check all links

Main todos:
- QC sheet update : session @mayofaulkner  [new sheet](https://docs.google.com/spreadsheets/d/1DV6Xfx4gGKOgb4rIPSsFO1tRYLPJAbIXGWzGqoO0Vlc/edit?gid=0#gid=0)
- QC sheet update : ephys raw + spike sorting -- do not update, but put current labels in Alyx, @oliche 
- Numbers: mice / insertions / units + good units / sessions @oliche 
- Mice age, weight @GaelleChapuis 
- coverage with 1 + 2 probes @GaelleChapuis 
- Fig 2 panel : 3D brain with insertions @mschart 
- Fig 2 panel: bar plot with N neurons @mschart 
- Video QC: raw, pose estimation, pupil @mayofaulkner @themattinthehatt

**Comment by Tkyzxim** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by GaelleChapuis** [comment]
Coverage:

0                4.068118
1                 7.85386
2               87.061564
date           2024-03-24
type          flip_metric

https://github.com/int-brain-lab/ibldevtools/blob/master/Gaelle/PhysWG/coverage/20220421__launch_coverage_gui_with_insertions_todo.py

**Comment by GaelleChapuis** [comment]
N subject: 139
AGE RANGE: 13-173 weeks; mean 44.35 weeks, median 27.0 weeks
WEIGHT RANGE: 16.1-35.7 g; mean 23.84 g, median 23.9 g

https://github.com/int-brain-lab/paper-brain-wide-map/blob/main/brainwidemap/meta/mice_info.py
