### ISSUE TITLE
Spike sorting white paper - publish and update docs

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/ibllib#838]
As part of the BW project, appendices need to be updated. 
https://github.com/int-brain-lab/project_registration/issues/32

- [x] Publish white paper on Figshare
- [x] update link and method in Data release white paper + BW paper

**Comment by oliche** [comment]
https://figshare.com/articles/online_resource/Spike_sorting_pipeline_for_the_International_Brain_Laboratory/19705522?file=49783080
