### ISSUE TITLE
Missing behavioral datasetTypes in ephys extraction

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/ibllib#88]
feedback_times, stimOn_times and stimOnTrigger_times are missing from the ephys extraction pipeline.
I suspect there are more, ephys should extract the same datasetTypes as behavior plus the ephys related datasetTypes

example session on Flatiron: /wittenlab/Subjects/ibl_witten_04/2019-08-04/002

related to #87

**Comment by GaelleChapuis** [comment]
Is that because of a hardware issue (i.e. things are not connected) or software (extraction) ?

**Comment by nbonacchi** [comment]
not data problem afaik, just some extractors missing
@oliche should be on top of this

**Comment by themattinthehatt** [comment]
@oliche can you let me know when this is done? I need to make some plots for the SCGB meeting that use the stimOn_times

**Comment by GaelleChapuis** [comment]
Done.
