### ISSUE TITLE
one.load suggestion

### ISSUE THREAD

**Issue by kdharris101** [int-brain-lab/ibllib#93]
Here is a suggestion for refactoring one.load. 

syntax: one.load(eid, dataset_type)

Inputs: 
eid: a single string. If you want to load multiple sessions, use a for loop.

dataset_type: a string or tuple of strings
* If it is a string of the form "object.attribute", return a numeric array containing that dataset.

* If it is a string of the form "object", return a bunch containing each attribute that object has

* If it is a tuple of strings, return a bunch of bunches.

Examples: 

`spike_times = one.load(eid, 'spikes.times')`
returns a single numeric array

`spikes = one.load(eid, 'spikes')`
returns a bunch with members, `spikes.times`, `spikes.clusters`, `spikes.amplitudes`, etc.

`data = one.load('spikes', 'clusters', 'eye.xy_pos')`, 
returns a bunch of bunches, with members `data.spikes.times`, `data.spikes.clusters`, ... etc for every attribute in `spikes`; `data.clusters.brain_location`, `data.clusters.quality`, ... etc for every attribute in `clusters`; and `data.eye.xy_pos`, i.e. only one attribute `xy_pos` for eye.

**Comment by jaib1** [comment]
Sorry @oliche I forget where this stands - is this

> eid: a single string. If you want to load multiple sessions, use a for loop.

the approach we're going with?

I am particularly in favor of doing this:

> If it is a string of the form "object", return a bunch containing each attribute that object has
If it is a tuple of strings, return a bunch of bunches.

**Comment by rossant** [comment]
closing here, to be discussed in the ONE v2 proposal
