### ISSUE TITLE
feedback times are sometimes NaN in ephys rig biasedChoiceWorld

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/ibllib#95]
**Describe the bug**
Several mice are training in biasedChoiceWorld on the ephys rig in the Churchland lab. Each of these sessions have `feedbacktimes` that are `nan`. 

**To Reproduce**
Example session: `4865b2c8-cc10-47d6-baee-4d500800d27a` has about half of feedbacktimes `nan`.

**Additional context**
For now, @shanshen is allowing feedbackTimes to be nullable.

**Comment by oliche** [comment]
@nbonacchi this is a no BNC2 problem so all error trials don't have feedback time.
I'm pushing something on ibllib that at least flags it in the extraction log but it's a hardware issue.

Still think they shouldn't be able to run their rigs without a BNC1/BNC2 ping

**Comment by GaelleChapuis** [comment]
@oliche was this hardware disconnect caught in the latest TTL test?

Is the BNC only disconnected on the Bpod, or also PFGA?
(it's easy to test on the Bpod, more work on the FPGA due to extraction)
